// Serializable versions — Maps converted to arrays for JSON transfer

export interface RoadNode {
  id: string; lat: number; lng: number; trafficSignalId?: string;
}

export interface RoadEdge {
  id: string; from: string; to: string;
  name: string; roadType: string; speedLimit: number; length: number;
  bearing: number; lanes: number; geometry: { lat: number; lng: number }[];
}

export interface RoadGraph {
  nodes: RoadNode[];
  edges: RoadEdge[];
  adjacency: [string, string[]][];
}

export interface SignalPhase {
  group: string; color: string; duration: number; yellowDuration: number;
}

export interface TrafficSignal {
  id: string; nodeId: string;
  phases: SignalPhase[];
  currentPhaseIndex: number; timer: number;
  cycleLength: number; offset: number;
  greenWaveDirection: string | null;
  congestionLevel: number; adaptiveTiming: boolean;
  approaches: { edgeId: string; bearing: number; color: string; duration: number }[];
}

export interface Vehicle {
  id: string; lat: number; lng: number;
  speed: number; bearing: number;
  type: string; color: string;
  isNavigated: boolean;
}

export interface CongestionZone {
  centerLat: number; centerLng: number;
  level: number; vehicles: number;
}

export interface TrafficStats {
  totalVehicles: number; avgSpeed: number; avgDelay: number;
  congestionHotspots: number; greenWaveActive: boolean;
  signalCoordinationScore: number; throughput: number; maxCongestion: number;
  slaSpeed: number; slaCompliant: boolean;
  emergencySlaSpeed: number; activeCorridors: number;
  /** Vehicles generated by the simulation */
  simulatedVehicles?: number;
  /** Vehicles of navigating users (GPS-driven or simulated drive) */
  realVehicles?: number;
}

export interface RouteInfo {
  /** Node IDs from source to destination */
  path: string[];
  /** Directed edge IDs traversed, in order */
  edgeIds: string[];
  /** Metres */
  distance: number;
  /** Seconds, including live congestion, other navigators and signal delay */
  estimatedTime: number;
  signalCount: number;
  /** Distinct road names in travel order */
  roadNames: string[];
  /** Full road geometry for drawing */
  geometry: { lat: number; lng: number }[];
  /** Most other active navigators sharing any single edge of this route */
  sharedUsers: number;
}
